services:
  postgres:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: pulseflow
      POSTGRES_USER: pulseflow
      POSTGRES_PASSWORD: pulseflow-local-password
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pulseflow", "-d", "pulseflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.1-alpine
    environment:
      RABBITMQ_DEFAULT_USER: pulseflow
      RABBITMQ_DEFAULT_PASS: pulseflow-local-password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15692:15692"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:8.4-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrations:
    build:
      context: .
      dockerfile: src/PulseFlow.Api/Dockerfile
      target: migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    command:
      - dotnet
      - ef
      - database
      - update
      - --connection
      - Host=postgres;Port=5432;Database=pulseflow;Username=pulseflow;Password=pulseflow-local-password

  api:
    build:
      context: .
      dockerfile: src/PulseFlow.Api/Dockerfile
      target: final
    environment:
      ASPNETCORE_URLS: "http://+:8080"

      ConnectionStrings__PulseFlow: Host=postgres;Port=5432;Database=pulseflow;Username=pulseflow;Password=pulseflow-local-password
      ConnectionStrings__RabbitMq: amqp://pulseflow:pulseflow-local-password@rabbitmq:5672/
      ConnectionStrings__Redis: redis:6379,abortConnect=false

      RabbitMq__QueueName: pulseflow.ingestion-batches
      RabbitMq__ConsumerCount: 1

      Ingestion__ChunkCapacity: 100

      IngestionRateLimit__RequestLimit: 10000000
      IngestionRateLimit__WindowDuration: "00:01:00"

    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

    ports:
      - "5254:8080"

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
