name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 10.0.x

      - name: Restore .Net tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore PulseFlow.slnx

      - name: Build
        run: dotnet build PulseFlow.slnx --no-restore

      - name: Test
        run: dotnet test PulseFlow.slnx --no-build

      - name: Cheack format
        run: dotnet csharpier check .

      - name: Test runner
        run: echo "CI works"
